# Generated by Django 3.1.7 on 2022-01-31 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date activated')),
                ('duration', models.IntegerField(max_length=99999)),
                ('executed', models.BooleanField(default=False)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pump')),
            ],
        ),
    ]
